language: bash

services:
  - docker

env:
  - VERSION=4.0
  - VERSION=3.2
  - VERSION=3.0
  - VERSION=4.0-alpine
  - VERSION=3.2-alpine
  - VERSION=3.0-alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - image="redis-cluster:$VERSION"

script:
  - docker build -t "$image" $VERSION
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
